# Lambda Functions - Lab

## Introduction

In this lab, you'll get some hands-on practice creating and using lambda functions.

## Objectives
In this lab you will: 
* Create lambda functions to use as arguments of other functions   
* Use the `.map()` or `.apply()` method to apply a function to a pandas series or DataFrame

## Lambda Functions

In [1]:
import pandas as pd
df = pd.read_csv('Yelp_Reviews.csv', index_col=0)
df.head(2)

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g

## Simple arithmetic

Use a lambda function to create a new column called `'stars_squared'` by squaring the stars column.

In [2]:
# Your code here
df['stars_squared'] = df.stars.map(lambda x: x**2)

In [5]:
df.head(25)

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,25
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,1
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,25
11,UBv8heCQR0RPnUQG0zkXIQ,0,2016-09-23,0,HkYqGb0Gplmmk-xlHTRBoA,1,The score should be negative. Its HORRIBLE. Th...,0,NhOc64RsrTT1Dls50yYW8g,1
12,hdgYnadxg0GANhWOJabr2g,0,2014-08-23,0,RgqWdZA4xR023iP3T6jVfA,5,I went there twice and I am pretty happy with ...,0,NhOc64RsrTT1Dls50yYW8g,25
19,gZGsReG0VeX4uKViHTB9EQ,0,2017-08-16,0,51RHs_V_fjuistnuKxNpEg,5,Finally! After trying many Mexican restaurants...,0,5ngpW5tf3ep680eG1HxHzA,25
25,f-v1fvtnbdw_QQRsCnwH-g,0,2017-11-18,0,alI_kRKyEHfdHibYGgtJbw,1,I have to write a review on the Fractured Prun...,0,Fc_nb6N6Sdurqb-rwsY1Bw,1
26,yz66FIUPDKGhILDWzRLeKg,0,2017-11-18,0,85DRIjwPJOTb4q0qOlBstw,1,I wish i could tell you all about the food but...,1,Fc_nb6N6Sdurqb-rwsY1Bw,1
27,6qDRqHWqf0EeHupSUEBfKg,0,2015-12-10,0,GbiLIKmQPVCBtdNkTVdVSA,5,Wonderful! One of my favorite places. BBQ is e...,0,G22ITfVETYHtIhnn5lLRrQ,25
28,7AlULGZI1pHt0imODsqdkg,0,2012-02-12,0,UaHgsL0xS4UnJ_iKqeOk_w,5,The price is about the same as Quizinos. The s...,0,FjH3TH8OvHGLNEbzdEYlNg,25
29,th4pZ5LkoIIkb1Vmu_m2DA,0,2012-02-12,0,c4zzAD1S6721Fh-acCBy-g,4,The food was ok. You get a lot of food for the...,0,FjH3TH8OvHGLNEbzdEYlNg,16
30,nsSfCKW9KDB4COj9bzXApw,0,2012-02-12,0,TTBwocu2mvqJFJrwmJN0Sw,5,The staff were friendly and helpful. The food ...,1,FjH3TH8OvHGLNEbzdEYlNg,25
31,cP8ErpZfRzdVR5Fvks-pnQ,0,2012-02-12,0,-CresnnXQSHrQ85Ogm-Pqw,5,The staff were very helpful. We painted potter...,0,FjH3TH8OvHGLNEbzdEYlNg,25
32,Edr6SafmQrZa6CcFuItoqg,0,2014-06-03,0,U04YgYr4PiGUxB46J4xapg,2,Limited vegetarian options. Ordered Greek sala...,0,B7Fh30KQT1xPSGt_pIhRRA,4
35,SpJYus_184M2TdT7t52rIA,0,2016-11-18,0,s9cpVj40VR_yl0lXbZQe6w,5,I trust my vehicles here. Comparable prices. M...,0,zx_Op2OAOM_fRic9tU-jqA,25
40,qdC2h3MqCNussc5lhzL7gg,0,2015-11-05,0,AJ0IglpYAp2D0daOlVGIdg,1,This place doesn't even deserve 1 star. Horrib...,18,Ka7TIp74VHSa90rfdg4_2g,1
41,XgRDG9E_WLEbl8S-QUqQkQ,0,2015-11-05,0,5D_MsAJHrMa8QKkpE3g1Sg,5,The butter burger was cooked perfectly and jui...,0,Ka7TIp74VHSa90rfdg4_2g,25
42,awgoBwuhzlLGKEIverTGjQ,0,2017-01-21,0,5bWN_IN8MQGjJ6_ZIXffDw,5,Best location ever! I love love love the manag...,0,yyPHK6khPa4-ErV9U32x3A,25
74,iO3GuIiZxzv-iETGVnoeVA,0,2016-11-06,0,RW_mYzHYfdqn6g7xVgIcKg,4,This was a real fun time. Lots of laughs and e...,0,0pf5VuzE4_1pwj5NJHG5TQ,16
79,yz3KtngrF2PQrif8JW7gdw,0,2016-05-28,0,SLA1YP9doUc8h-6Kd34QmA,1,Horrible. The smart ones have closed their acc...,1,0pf5VuzE4_1pwj5NJHG5TQ,1
83,T2XdzAcj0M_kBD9_BHfZlw,0,2016-05-08,0,qxPiEGIHy5xyVy78avH5Rg,4,Love the 'old school' ambiance. Friendly staff...,1,0pf5VuzE4_1pwj5NJHG5TQ,16
92,AtbXj3Rg1GF6Dj5zu6KCDg,0,2012-10-11,0,q6ij-nz5d_hvdjuelho1pQ,5,Better service and much better prices than the...,0,WnM2AmNIint5b5f688nmPg,25
95,6tSvz_21BMo3a4GaItwa0g,0,2017-04-08,0,66FSK2J1uHJqVI1Z8QiFGw,4,I love how they have no rice sushi options. Th...,0,Yy_iGXxLpL6tYDQoE-6XVg,16

## Dates
Select the month from the date string using a lambda function.

In [ ]:
# Your code here

## What is the average number of words for a yelp review?
Do this with a single line of code!

In [ ]:
# Your code here

## Create a new column for the number of words in the review

In [ ]:
# Your code here

## Rewrite the following as a lambda function

Create a new column `'Review_Length'` by applying this lambda function to the `'Review_num_words'` column.

In [ ]:
# Rewrite the following function as a lambda function
def rewrite_as_lambda(value):
    if len(value) < 50:
        return 'Short'
    elif len(value) < 80:
        return 'Medium'
    else:
        return 'Long'
# Hint: nest your if, else conditionals

df['Review_length'] = None

## Level Up: Dates Advanced!
<img src="images/world_map.png" width="600">  

Print the first five rows of the `'date'` column.

In [ ]:
# Your code here

Overwrite the `'date'` column by reordering the month and day from `YYYY-MM-DD` to `DD-MM-YYYY`. Try to do this using a lambda function.

In [ ]:
# Your code here

## Summary

Great! Hopefully, you're getting the hang of lambda functions now! It's important not to overuse them - it will often make more sense to define a function so that it's reusable elsewhere. But whenever you need to quickly apply some simple processing to a collection of data you have a new technique that will help you to do just that. It'll also be useful if you're reading someone else's code that happens to use lambdas.